name: Ui Workflow
# on push we will trigger our code
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 #checkout the code
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Run Manual Tests
        run: |
          mvn clean verify -Dcucumber.filter.tags="@manual"

      - name: Produce report
        run: mvn serenity:aggregate

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: artifacts/screenshots

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/site